
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package at.jku.ce.ue.log;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2013-01-08T20:38:23.559+01:00
 * Generated source version: 2.4.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "WriteLogServiceService",
                      portName = "WriteLogServicePort",
                      targetNamespace = "http://ue.ce.jku.at/",
                      wsdlLocation = "http://140.78.73.87:8090/ACServices/services/WriteLogServicePort?wsdl",
                      endpointInterface = "at.jku.ce.ue.log.WriteLogService")
                      
public class WriteLogServiceImpl implements WriteLogService {

    private static final Logger LOG = Logger.getLogger(WriteLogServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see at.jku.ce.ue.log.WriteLogService#logInquiry(java.lang.String  customerid ,)java.lang.String  producerid ,)java.lang.String  partid ,)java.lang.String  inquiryid )*
     */
    public void logInquiry(java.lang.String customerid,java.lang.String producerid,java.lang.String partid,java.lang.String inquiryid) { 
        LOG.info("Executing operation logInquiry");
        System.out.println(customerid);
        System.out.println(producerid);
        System.out.println(partid);
        System.out.println(inquiryid);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.ue.log.WriteLogService#logOffer(java.lang.String  customerid ,)java.lang.String  producerid ,)java.lang.String  partid ,)int  price ,)java.lang.String  inquiryid ,)java.lang.String  offerid )*
     */
    public void logOffer(java.lang.String customerid,java.lang.String producerid,java.lang.String partid,int price,java.lang.String inquiryid,java.lang.String offerid) { 
        LOG.info("Executing operation logOffer");
        System.out.println(customerid);
        System.out.println(producerid);
        System.out.println(partid);
        System.out.println(price);
        System.out.println(inquiryid);
        System.out.println(offerid);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.ue.log.WriteLogService#logOrder(java.lang.String  customerid ,)java.lang.String  producerid ,)java.lang.String  partid ,)int  price ,)java.lang.String  inquiryid ,)java.lang.String  offerid ,)java.lang.String  orderid )*
     */
    public void logOrder(java.lang.String customerid,java.lang.String producerid,java.lang.String partid,int price,java.lang.String inquiryid,java.lang.String offerid,java.lang.String orderid) { 
        LOG.info("Executing operation logOrder");
        System.out.println(customerid);
        System.out.println(producerid);
        System.out.println(partid);
        System.out.println(price);
        System.out.println(inquiryid);
        System.out.println(offerid);
        System.out.println(orderid);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
