
package at.jku.ce.ue.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2013-01-08T20:35:59.692+01:00
 * Generated source version: 2.4.9
 * 
 */
public final class InquiryOrderPlattformService_InquiryOrderPlattformServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ue.ce.jku.at/", "InquiryOrderPlattformServiceService");

    private InquiryOrderPlattformService_InquiryOrderPlattformServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = InquiryOrderPlattformServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        InquiryOrderPlattformServiceService ss = new InquiryOrderPlattformServiceService(wsdlURL, SERVICE_NAME);
        InquiryOrderPlattformService port = ss.getInquiryOrderPlattformServicePort();  
        
        {
        System.out.println("Invoking getPrice...");
        java.lang.String _getPrice_customerid = "_getPrice_customerid-1451046159";
        java.lang.String _getPrice_producerid = "_getPrice_producerid602667497";
        java.lang.String _getPrice_partid = "_getPrice_partid1779380594";
        java.lang.String _getPrice_inquiryid = "_getPrice_inquiryid-1098442720";
        int _getPrice__return = port.getPrice(_getPrice_customerid, _getPrice_producerid, _getPrice_partid, _getPrice_inquiryid);
        System.out.println("getPrice.result=" + _getPrice__return);


        }
        {
        System.out.println("Invoking getAllPartsByProducer...");
        java.lang.String _getAllPartsByProducer_producerid = "_getAllPartsByProducer_producerid-598938148";
        java.util.List<java.lang.String> _getAllPartsByProducer__return = port.getAllPartsByProducer(_getAllPartsByProducer_producerid);
        System.out.println("getAllPartsByProducer.result=" + _getAllPartsByProducer__return);


        }
        {
        System.out.println("Invoking getAllPartsOnPlattform...");
        java.util.List<java.lang.String> _getAllPartsOnPlattform__return = port.getAllPartsOnPlattform();
        System.out.println("getAllPartsOnPlattform.result=" + _getAllPartsOnPlattform__return);


        }
        {
        System.out.println("Invoking getAllProducersForPart...");
        java.lang.String _getAllProducersForPart_partid = "_getAllProducersForPart_partid-161031901";
        java.util.List<java.lang.String> _getAllProducersForPart__return = port.getAllProducersForPart(_getAllProducersForPart_partid);
        System.out.println("getAllProducersForPart.result=" + _getAllProducersForPart__return);


        }
        {
        System.out.println("Invoking placeOrder...");
        java.lang.String _placeOrder_customerid = "_placeOrder_customerid-1413873558";
        java.lang.String _placeOrder_producerid = "_placeOrder_producerid-77076697";
        java.lang.String _placeOrder_partid = "_placeOrder_partid84233867";
        java.lang.String _placeOrder_inquiryid = "_placeOrder_inquiryid-2019043161";
        int _placeOrder_price = -90363332;
        java.lang.String _placeOrder_orderid = "_placeOrder_orderid-1211148437";
        port.placeOrder(_placeOrder_customerid, _placeOrder_producerid, _placeOrder_partid, _placeOrder_inquiryid, _placeOrder_price, _placeOrder_orderid);


        }
        {
        System.out.println("Invoking getAllProducersOnPlattform...");
        java.util.List<java.lang.String> _getAllProducersOnPlattform__return = port.getAllProducersOnPlattform();
        System.out.println("getAllProducersOnPlattform.result=" + _getAllProducersOnPlattform__return);


        }

        System.exit(0);
    }

}
