package at.jku.ce.ue.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2013-01-08T20:35:59.790+01:00
 * Generated source version: 2.4.9
 * 
 */
@WebService(targetNamespace = "http://ue.ce.jku.at/", name = "InquiryOrderPlattformService")
@XmlSeeAlso({ObjectFactory.class})
public interface InquiryOrderPlattformService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPrice", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetPrice")
    @WebMethod(action = "urn:GetPrice")
    @ResponseWrapper(localName = "getPriceResponse", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetPriceResponse")
    public int getPrice(
        @WebParam(name = "customerid", targetNamespace = "")
        java.lang.String customerid,
        @WebParam(name = "producerid", targetNamespace = "")
        java.lang.String producerid,
        @WebParam(name = "partid", targetNamespace = "")
        java.lang.String partid,
        @WebParam(name = "inquiryid", targetNamespace = "")
        java.lang.String inquiryid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllPartsByProducer", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetAllPartsByProducer")
    @WebMethod(action = "urn:GetAllPartsByProducer")
    @ResponseWrapper(localName = "getAllPartsByProducerResponse", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetAllPartsByProducerResponse")
    public java.util.List<java.lang.String> getAllPartsByProducer(
        @WebParam(name = "producerid", targetNamespace = "")
        java.lang.String producerid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllPartsOnPlattform", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetAllPartsOnPlattform")
    @WebMethod(action = "urn:GetAllPartsOnPlattform")
    @ResponseWrapper(localName = "getAllPartsOnPlattformResponse", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetAllPartsOnPlattformResponse")
    public java.util.List<java.lang.String> getAllPartsOnPlattform();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllProducersForPart", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetAllProducersForPart")
    @WebMethod(action = "urn:GetAllProducersForPart")
    @ResponseWrapper(localName = "getAllProducersForPartResponse", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetAllProducersForPartResponse")
    public java.util.List<java.lang.String> getAllProducersForPart(
        @WebParam(name = "partid", targetNamespace = "")
        java.lang.String partid
    );

    @RequestWrapper(localName = "placeOrder", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.PlaceOrder")
    @WebMethod(action = "urn:PlaceOrder")
    @ResponseWrapper(localName = "placeOrderResponse", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.PlaceOrderResponse")
    public void placeOrder(
        @WebParam(name = "customerid", targetNamespace = "")
        java.lang.String customerid,
        @WebParam(name = "producerid", targetNamespace = "")
        java.lang.String producerid,
        @WebParam(name = "partid", targetNamespace = "")
        java.lang.String partid,
        @WebParam(name = "inquiryid", targetNamespace = "")
        java.lang.String inquiryid,
        @WebParam(name = "price", targetNamespace = "")
        int price,
        @WebParam(name = "orderid", targetNamespace = "")
        java.lang.String orderid
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllProducersOnPlattform", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetAllProducersOnPlattform")
    @WebMethod(action = "urn:GetAllProducersOnPlattform")
    @ResponseWrapper(localName = "getAllProducersOnPlattformResponse", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.client.GetAllProducersOnPlattformResponse")
    public java.util.List<java.lang.String> getAllProducersOnPlattform();
}
