
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package at.jku.ce.ue.bom;

import java.util.logging.Logger;

import at.jku.ce.ue.source.businessLogic.impl.PartServiceImpl;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2013-01-08T20:36:50.323+01:00
 * Generated source version: 2.4.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "BOMServiceService",
                      portName = "BOMServicePort",
                      targetNamespace = "http://ue.ce.jku.at/",
                      wsdlLocation = "http://140.78.73.87:8090/ACServices/services/BOMServicePort?wsdl",
                      endpointInterface = "at.jku.ce.ue.bom.BOMService")
                      
public class BOMServiceImpl implements BOMService {

    private static final Logger LOG = Logger.getLogger(BOMServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see at.jku.ce.ue.bom.BOMService#getDirectSubPartsOf(java.lang.String  arg0 )*
     */
    public java.util.List<java.lang.String> getDirectSubPartsOf(java.lang.String arg0) { 
        LOG.info("Executing operation getDirectSubPartsOf");
        System.out.println(arg0);
        try {
        	
        	PartServiceImpl partService = new PartServiceImpl();
        	return partService.getDirectSubPartsOf(arg0);
        	
        	
//            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
//            java.lang.String _returnVal1 = "_returnVal1875170331";
//            _return.add(_returnVal1);
//            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.ue.bom.BOMService#setDirectSubPartsOf(java.lang.String  arg0 ,)java.util.List<java.lang.String>  arg1 )*
     */
    public void setDirectSubPartsOf(java.lang.String arg0,java.util.List<java.lang.String> arg1) { 
        LOG.info("Executing operation setDirectSubPartsOf");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see at.jku.ce.ue.bom.BOMService#getAllParts(*
     */
    public java.util.List<java.lang.String> getAllParts() { 
        LOG.info("Executing operation getAllParts");
        try {
        	
        	PartServiceImpl partService = new PartServiceImpl();
        	return partService.getAllPartNames();
//        	
//            java.util.List<java.lang.String> _return = new java.util.ArrayList<java.lang.String>();
//            java.lang.String _returnVal1 = "_returnVal-790490089";
//            _return.add(_returnVal1);
//            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
