
package at.jku.ce.ue.bom;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2013-01-08T20:36:50.245+01:00
 * Generated source version: 2.4.9
 * 
 */
public final class BOMService_BOMServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ue.ce.jku.at/", "BOMServiceService");

    private BOMService_BOMServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BOMServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BOMServiceService ss = new BOMServiceService(wsdlURL, SERVICE_NAME);
        BOMService port = ss.getBOMServicePort();  
        
        {
        System.out.println("Invoking getDirectSubPartsOf...");
        java.lang.String _getDirectSubPartsOf_arg0 = "_getDirectSubPartsOf_arg0251397381";
        java.util.List<java.lang.String> _getDirectSubPartsOf__return = port.getDirectSubPartsOf(_getDirectSubPartsOf_arg0);
        System.out.println("getDirectSubPartsOf.result=" + _getDirectSubPartsOf__return);


        }
        {
        System.out.println("Invoking setDirectSubPartsOf...");
        java.lang.String _setDirectSubPartsOf_arg0 = "_setDirectSubPartsOf_arg0-152727467";
        java.util.List<java.lang.String> _setDirectSubPartsOf_arg1 = new java.util.ArrayList<java.lang.String>();
        java.lang.String _setDirectSubPartsOf_arg1Val1 = "_setDirectSubPartsOf_arg1Val-1590973786";
        _setDirectSubPartsOf_arg1.add(_setDirectSubPartsOf_arg1Val1);
        port.setDirectSubPartsOf(_setDirectSubPartsOf_arg0, _setDirectSubPartsOf_arg1);


        }
        {
        System.out.println("Invoking getAllParts...");
        java.util.List<java.lang.String> _getAllParts__return = port.getAllParts();
        System.out.println("getAllParts.result=" + _getAllParts__return);


        }

        System.exit(0);
    }

}
