package at.jku.ce.ue.bom;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2013-01-08T20:36:50.356+01:00
 * Generated source version: 2.4.9
 * 
 */
@WebServiceClient(name = "BOMServiceService", 
                  wsdlLocation = "http://140.78.73.87:8090/ACServices/services/BOMServicePort?wsdl",
                  targetNamespace = "http://ue.ce.jku.at/") 
public class BOMServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ue.ce.jku.at/", "BOMServiceService");
    public final static QName BOMServicePort = new QName("http://ue.ce.jku.at/", "BOMServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://140.78.73.87:8090/ACServices/services/BOMServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BOMServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://140.78.73.87:8090/ACServices/services/BOMServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BOMServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BOMServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BOMServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BOMService
     */
    @WebEndpoint(name = "BOMServicePort")
    public BOMService getBOMServicePort() {
        return super.getPort(BOMServicePort, BOMService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BOMService
     */
    @WebEndpoint(name = "BOMServicePort")
    public BOMService getBOMServicePort(WebServiceFeature... features) {
        return super.getPort(BOMServicePort, BOMService.class, features);
    }

}
