package at.jku.ce.ue.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2013-01-08T20:34:27.297+01:00
 * Generated source version: 2.4.9
 * 
 */
@WebServiceClient(name = "InquiryOrderPlattformServiceService", 
                  wsdlLocation = "http://140.78.73.87:8090/ACServices/services/InquiryOrderPlattformServicePort?wsdl",
                  targetNamespace = "http://ue.ce.jku.at/") 
public class InquiryOrderPlattformServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ue.ce.jku.at/", "InquiryOrderPlattformServiceService");
    public final static QName InquiryOrderPlattformServicePort = new QName("http://ue.ce.jku.at/", "InquiryOrderPlattformServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://140.78.73.87:8090/ACServices/services/InquiryOrderPlattformServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InquiryOrderPlattformServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://140.78.73.87:8090/ACServices/services/InquiryOrderPlattformServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InquiryOrderPlattformServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InquiryOrderPlattformServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InquiryOrderPlattformServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns InquiryOrderPlattformService
     */
    @WebEndpoint(name = "InquiryOrderPlattformServicePort")
    public InquiryOrderPlattformService getInquiryOrderPlattformServicePort() {
        return super.getPort(InquiryOrderPlattformServicePort, InquiryOrderPlattformService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InquiryOrderPlattformService
     */
    @WebEndpoint(name = "InquiryOrderPlattformServicePort")
    public InquiryOrderPlattformService getInquiryOrderPlattformServicePort(WebServiceFeature... features) {
        return super.getPort(InquiryOrderPlattformServicePort, InquiryOrderPlattformService.class, features);
    }

}
