package at.jku.ce.ue.bom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.9
 * 2013-01-08T20:36:50.344+01:00
 * Generated source version: 2.4.9
 * 
 */
@WebService(targetNamespace = "http://ue.ce.jku.at/", name = "BOMService")
@XmlSeeAlso({ObjectFactory.class})
public interface BOMService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDirectSubPartsOf", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.bom.GetDirectSubPartsOf")
    @WebMethod(action = "urn:GetDirectSubPartsOf")
    @ResponseWrapper(localName = "getDirectSubPartsOfResponse", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.bom.GetDirectSubPartsOfResponse")
    public java.util.List<java.lang.String> getDirectSubPartsOf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "setDirectSubPartsOf", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.bom.SetDirectSubPartsOf")
    @WebMethod(action = "urn:SetDirectSubPartsOf")
    @ResponseWrapper(localName = "setDirectSubPartsOfResponse", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.bom.SetDirectSubPartsOfResponse")
    public void setDirectSubPartsOf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllParts", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.bom.GetAllParts")
    @WebMethod(action = "urn:GetAllParts")
    @ResponseWrapper(localName = "getAllPartsResponse", targetNamespace = "http://ue.ce.jku.at/", className = "at.jku.ce.ue.bom.GetAllPartsResponse")
    public java.util.List<java.lang.String> getAllParts();
}
